[book]
authors = ["Alex The Entreprenerd", "nican0r"]
language = "en"
multilingual = false
src = "src"
title = "Recon Docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["theme/toc.css"]
additional-js = ["theme/toc.js"]